#!/usr/bin/env python3
from pathlib import Path
import re, sys
ROOT = Path(__file__).resolve().parents[1]
read = lambda p: (ROOT / p).read_text(encoding='utf-8')
ctl = read('src/DuelController.cs')
policy = read('src/DuelSafetyPolicy.cs')
plugin = read('src/ErenshorDuelPlugin.cs')
build = read('src/DuelBuildInfo.cs')
events = read('src/DuelEventContract.cs')
api = read('src/PracticeDuelIntegrationApi.cs')
checks=[]
def ck(name, cond): checks.append((name, bool(cond)))

def section(start, end):
    a=ctl.find(start); b=ctl.find(end, a+1)
    return '' if a < 0 or b < 0 else ctl[a:b]

stop = section('private static void StopInternal', 'private static void BeginPostDuelAttackCleanup')
begin = section('private static void BeginPostDuelAttackCleanup', 'private static void RunPostDuelAttackCleanup')
cleanup = section('private static void RunPostDuelAttackCleanup', 'private static void FlushDeferredAggroTargets')
force = section('private static void ForceStopPlayerAttack()', 'private static bool ReadGlobalAutoattacking')
prepare = section('internal static bool PrepareNativeDamage', 'internal static void FinishNativeDamage')
try_virtual = section('internal static bool TryVirtualDamage', 'internal static void ApplyVirtualDamage')
status = section('internal static bool BeginStatusEffect', 'internal static void FinishStatusEffect')
combat = section('internal static bool AdmitNativeCombat', 'private static void LogPreActiveDuelCombat')
allow_action = section('internal static bool AllowCombatAction', 'internal sealed class SpellStartState')
allow_aggro = section('internal static bool AllowAggro', 'internal static bool AllowManageAggro')
force_on = section('internal static bool AllowPlayerAutomaticAttackOn()', 'private static void SnapshotPostDuelPets')

ck('version 0.5.1', 'PluginVersion = "0.5.1"' in plugin)
ck('build id 0.5.1 terminal cleanup', '0.5.1-terminal-combat-cleanup' in build)
ck('player native attack ownership observed at PerformAttacks', 'ObservePlayerNativeAttack' in ctl and 'HarmonyPatch(typeof(PlayerCombat), "PerformAttacks"' in ctl)
ck('automatic native rearm patched at ForceAttackOn', 'HarmonyPatch(typeof(PlayerCombat), "ForceAttackOn")' in ctl and 'AllowPlayerAutomaticAttackOn' in ctl)
ck('manual ToggleAttack remains unpatched', 'HarmonyPatch(typeof(PlayerCombat), "ToggleAttack")' not in ctl)
ck('private PlayerCombat.Autoattack cleared', 'PlayerAutoattackField.SetValue(GameData.PlayerCombat, false)' in force)
ck('static GameData.Autoattacking cleared', 'GameData.Autoattacking = false' in force)
ck('native ForceAttackOff retained', 'GameData.PlayerCombat.ForceAttackOff()' in force)
ck('attack cadence timers not rewritten', all(x not in force+cleanup+stop for x in ['CurrentMHAtkDelay =','CurrentOHAtkDelay =','ResetMHAtkDelay(','ResetOHAtkDelay(','ZeroMHAtkDelay(','ZeroOHAtkDelay(']))
ck('ownership requires native attack state plus duel correlation', 'OwnsTerminalPlayerAttack' in policy and '_playerDuelAttackIntentObserved' in begin and 'currentTargetIsOpponent' in begin)
ck('unrelated current target releases Duel attack ownership', 'reason=unrelated_current_target' in ctl and '_postDuelPlayerAttackOwned = false' in ctl)
ck('Duel opponent selection is preserved', 'CurrentTarget = null' not in cleanup and 'targetPreserved=' in ctl)
ck('terminal stop uses ownership helper', 'StopOwnedPlayerAttackIfNeeded("Stop.Terminal")' in stop)
ck('Cleaning repeats only ownership-aware stop', 'StopOwnedPlayerAttackIfNeeded("Cleaning.Tick")' in cleanup)
ck('bounded automatic-rearm tombstone', 'TerminalAutomaticRearmGuardSeconds = 6f' in ctl and '_terminalAutoRearmGuardUntil' in ctl and 'if (!_spectatorDuel && _playerDuelAttackIntentObserved &&' in ctl and '(currentTargetIsOpponent || currentTargetIsNull)' in ctl)
ck('PvP conflict exempts automatic rearm blocking', 'DuelPvpCompatibility.HasConflict()' in force_on and 'pvpConflict' in force_on)
ck('unrelated target exempts automatic rearm blocking', 'ShouldBlockTerminalAutomaticRearm' in policy and 'currentTargetIsOpponent || currentTargetIsNull' in policy)
ck('queued participant damage suppressed before Active gate', prepare.find('SuppressPostDuelParticipantDamage') >= 0 and prepare.find('SuppressPostDuelParticipantDamage') < prepare.find('if (!Active) return true;'))
ck('direct participant damage also terminal-contained', 'internal static bool TryVirtualDamage' in ctl and re.search(r'internal static bool TryVirtualDamage[\s\S]{0,500}SuppressPostDuelParticipantDamage[\s\S]{0,250}if \(!Active', ctl) is not None)
ck('post-terminal status effects contained', 'IsPostDuelParticipantEdge(target.Myself, source)' in status and status.find('IsPostDuelParticipantEdge') < status.find('if (!Active) return true;'))
ck('world hostile edge not classified as former participant edge', 'sourcePrincipal == _postDuelPlayer' in ctl and 'sourcePrincipal == _postDuelSim' in ctl and 'OutsideHostile' not in policy[policy.find('ShouldSuppressTerminalParticipantEdge'):policy.find('ShouldRestoreInitialEnemyMembership')])
ck('Sim aggro toward former opponent suppressed', 'terminal_sim_aggro_suppressed' in allow_aggro)
ck('Sim spell/skill action toward former opponent suppressed', 'terminal_sim_action_suppressed' in allow_action)
ck('Sim new native Combat frame toward former opponent suppressed', 'terminal_sim_combat_suppressed' in combat)
ck('Sim hostile-world combat remains native', 'Classify(current) == CombatActorClass.OutsideHostile' in allow_action and 'Classify(current) == CombatActorClass.OutsideHostile' in combat)
ck('already-running NPC Combat is still finalized safely', 'BeginNativeCombat' in ctl and 'EndNativeCombat' in ctl and 'DeferredAggroTargets' in ctl)
ck('zone transition clears stale automatic-rearm correlation', 'ClearTerminalAutoRearmGuard("scene_transition_cancelled")' in ctl and 'ClearTerminalAutoRearmGuard("scene_transition_idle")' in ctl)
ck('new player duel clears old terminal guard', 'ClearTerminalAutoRearmGuard("new_player_duel")' in ctl)
ck('new Sim-v-Sim duel clears old terminal guard', 'ClearTerminalAutoRearmGuard("new_spectator_duel")' in ctl)
ck('player yield path still reaches Stop', 'Stop(ParticipantLabel(state.Target) + " yields. Friendly duel complete!")' in ctl or 'Stop(ParticipantLabel(target) + " yields. Friendly duel complete!")' in ctl)
ck('opponent yield path still reaches Stop', 'yields. Friendly duel complete!' in ctl)
ck('manual stop routes controller Stop', '/eduel stop' in plugin and 'DuelController.Stop(' in plugin)
ck('zone cancellation routes terminal Stop', 'Cancel("Scene.Transition"' in ctl and 'Stop(reason)' in ctl)
ck('v4 event contract preserved', 'public const int ContractVersion = 4' in events)
ck('v2 autonomous API preserved', 'public static class PracticeDuelIntegrationApiV2' in api and 'public const int ContractVersion = 2' in api)
ck('terminal event retains RequestId/DuelId', 'public string RequestId' in events and 'public string DuelId' in events and '_eventContext' in stop)
ck('terminal factual result is built before ClearSessionState', stop.find('DuelEventFactory.Completed') >= 0 and stop.find('DuelEventFactory.Completed') < stop.find('ClearSessionState()'))
ck('terminal event published after factual result/state clear', stop.find('ClearSessionState()') >= 0 and stop.find('NotifyDuelEvent(lifecycleEvent') > stop.find('ClearSessionState()'))
ck('terminal event exact-once ownership comment/gate retained', 'Exactly one terminal event is emitted' in stop and 'if (wasActive && completed)' in stop)
ck('participant-only semantic contract has no invented witness field', 'Witness' not in events and 'Observer' not in events)

for name, ok in checks:
    print(('PASS ' if ok else 'FAIL ') + name)
fails=[name for name,ok in checks if not ok]
print(f'Practice Duel terminal combat cleanup source acceptance: {len(checks)-len(fails)}/{len(checks)} pass')
if fails: print('Failures: ' + '; '.join(fails))
sys.exit(1 if fails else 0)
