#!/usr/bin/env python3
from pathlib import Path
import re, sys
ROOT = Path(__file__).resolve().parents[1]
read = lambda p: (ROOT / p).read_text(encoding='utf-8')
controller = read('src/DuelController.cs')
plugin = read('src/ErenshorDuelPlugin.cs')
control = read('src/DuelControlApi.cs')
events = read('src/DuelEventContract.cs')
api = read('src/PracticeDuelIntegrationApi.cs')
auto = read('src/DuelAutonomousPolicy.cs')
challenge = read('src/DuelChallengePolicy.cs')
pvp = read('src/DuelPvpCompatibility.cs')
settings = read('src/DuelSettings.cs')
safety = read('src/DuelSafetyPolicy.cs')
combat = read('src/DuelCombatSemanticsPolicy.cs')
checks=[]
def ck(name, cond): checks.append((name, bool(cond)))
ck('version 0.5.0', 'PluginVersion = "0.5.0"' in plugin)
ck('v1 control API preserved', 'public const int ApiVersion = 1' in control)
ck('v1 autonomous API preserved', 'public static class PracticeDuelIntegrationApi' in api and 'ContractVersion = 1' in api and 'RequestAutonomousChallenge(string opponentName, string source)' in api)
ck('additive autonomous API v2', 'PracticeDuelIntegrationApiV2' in api and 'ContractVersion = 2' in api and 'RequestPlayerChallenge' in api and 'RequestSimSpar' in api)
ck('v4 semantic event contract', 'PracticeDuelEvents' in events and 'ContractVersion = 4' in events)
ck('request metadata complete', all(x in events+api for x in ['RequestId','DuelId','Source','Origin','ParticipantA','ParticipantB','RequestedUtcTicks']))
ck('requested event published', 'duel_requested' in events and 'PublishAutonomousRequested' in plugin and 'PublishAutonomousRequested' in controller)
ck('nonparty local path admitted', 'candidatePartySim &&' in controller and '!candidatePartySim && !IsUsableSim(sim)' in controller and 'ChallengeDistance' in controller)
ck('party path retained', 'IsPlayerPartySim(sim)' in controller and 'partySim ? "PARTY" : "NEARBY"' in controller)
ck('off-map locality rejected', 'IsSimLocalToActiveZone' in controller and 'WrongScene' in read('src/DuelEligibilityPolicy.cs'))
ck('remote COOP rejected', 'CoopCompatibility.IsRemoteHuman' in controller)
ck('real combat gate retained', 'HasUnsafeRealCombat' in controller)
ck('camp conflict gate retained', 'IsCampActive' in controller)
ck('Sim-v-Sim explicit command path retained', 'StartSpectator(first, second, DuelRequestOrigin.ExplicitPlayer)' in plugin)
ck('Sim-v-Sim full lifecycle events', all(x in controller for x in ['SpectatorChallenge','SpectatorAccepted','SpectatorStarted','SpectatorCompleted','SpectatorCancelled']))
ck('Sim-v-Sim refusal event', 'SpectatorDeclined' in controller and 'decline_willingness' in controller)
ck('nonlethal yield preserved', 'FinishPercent = 5' in controller and 'virtual' in combat.lower())
ck('native damage transaction preserved', 'CaptureNativeReduceHp' in controller and 'CurrentHP = int.MaxValue' not in controller)
ck('self healing adaptation retained', 'SelfOnly' in controller and 'ApplyToCaster' in controller and 'InflictOnSelf' in controller)
ck('player current target restoration retained', '_previousPlayerTarget' in controller and 'ShouldRestorePreviousTarget' in controller)
ck('world hostile coexistence retained', 'Hostile-world PvE may overlap an active Practice Duel' in controller)
ck('cleanup state retained', 'RestoreRealHealthAndEffects()' in controller and 'ClearSessionState()' in controller and 'BeginPostDuelAttackCleanup()' in controller)
ck('explicit/autonomous cooldown separated', 'RecentDuelWindowSeconds' in challenge and 'ExplicitPlayer' in challenge and 'Autonomous' in challenge)
ck('autonomous player willingness Duel-owned', 'DeclineAutonomousPreference' in challenge and '|practice' in challenge)
ck('ambient optional default off', 'AmbientSparringEnabled = false' in settings)
ck('ambient many-minute cadence', 'AmbientMinimumMinutes = 20' in settings and 'AmbientMaximumMinutes = 35' in settings)
ck('ambient strong per-Sim cooldown', 'AmbientPerSimCooldownMinutes = 60' in settings and 'LastAmbientSparBySim' in controller)
ck('ambient rare admission', 'AmbientOpportunityPercent = 20' in settings and 'DeterministicPercent(opportunityKey + "|admit")' in controller)
ck('ambient independent willingness', 'AmbientPairWilling' in controller and 'AmbientCandidateWilling(first' in controller and 'AmbientCandidateWilling(second' in controller)
ck('ambient adequate health', 'MinimumAmbientHealthPercent = 60' in auto)
ck('ambient bounded level relation', 'MaximumAmbientLevelGap = 6' in auto)
ck('ambient unsafe world states blocked', all(x in controller for x in ['GameData.InCharSelect','GameData.Zoning','DuelPvpCompatibility.HasConflict()','HasAmbientNearbyThreat','IsCampActive(false)']))
ck('ambient no remote actors', 'EvaluateEligibility(sim, player' in controller and 'CoopCompatibility.IsRemoteHuman' in controller)
ck('PvP conflict API read-only', 'PvpControlApi' in pvp and 'GetBasicState' in pvp and 'EncounterActive' in pvp and 'PendingOpponent' in pvp)
ck('PARTY/NEARBY structured candidates', 'DuelCandidateInfo' in control and 'EligibleCandidates' in control and 'Scope' in control)
ck('stable request/duel correlation reaches terminal events', 'SpectatorCompleted(\n                        _eventContext' in controller and 'Completed(completedSimName' in controller and '_eventContext' in controller)
ck('autonomous rejection preserves allocated duel id', 'RejectAutonomousRequest(requestContext, ReadName(target)' in controller and 'RejectAutonomousRequest(request.Context()' in controller)
ck('spectator transition failure is terminal', 'SpectatorCancelled(requestContext, "internal_error"' in controller)
ck('semantic facts include generic correlation fallback', 'request_id' in events and 'duel_id' in events and 'participant_a' in events and 'participant_b' in events)
ck('source system identified', 'SourceSystem = "practice_duel"' in events and 'source_system' in events)
ck('ambient schedule resets on zone transition', '_nextAmbientSparAt = -1f' in controller and 'HandleSceneTransition' in controller)
ck('ambient diagnostics observable', 'ambientEnabled=' in controller and 'ambientNextSeconds=' in controller and 'pvpConflict=' in controller)
ck('no off-map proxy creation', 'new SimPlayer' not in controller and 'FindObjectsOfType<SimPlayer>()' in controller)
for n,o in checks: print(('PASS ' if o else 'FAIL ')+n)
f=[n for n,o in checks if not o]
print(f'Practice Duel rivalry expansion source acceptance: {len(checks)-len(f)}/{len(checks)} pass')
if f: print('Failures: '+'; '.join(f))
sys.exit(1 if f else 0)
